paths:
  repo_root: "/homes/hussain/hussain-simulation_hdx/projects/aSyn_simulations"
  gmx: "/ceph/opig-shared/apps/gromacs-2026/bin/gmx"
  output_dir: "topology_output"
  conda_env: "amber"
  resp_env: "psiresp_fixed"

charge_settings:
  method: "resp"
  basis_set: "6-31G*"
  functional: "B3LYP"
  n_conformers: 1  # For testing, usually 2-5 for RESP

protein:
  input_pdb: "templates/protein/aSyn_s20_r1_msa1-127_n12700_do1_20260329_025853_protonated_max_plddt_12691.pdb"
  forcefield: "amber19sb"
  water_model: "opc"

conditions:
  saline:
    ph: 7.4
    ligands: []
  tris:
    ph: 7.4
    ligands: [TR1, TR0]
  extracellular:
    ph: 7.4
    ligands: [TR1, TR0]
  intracellular:
    ph: 7.2
    ligands: [TR1, TR0]
  lysosomal:
    ph: 4.9
    ligands: [CI1, CI2]

ligands:
  TR1:
    mol2: "templates/mol2/tris.mol2"
    net_charge: 1
    resname: "TR1"
    charge_method: "bcc"
    description: "Tris+ buffer cation"



  TR0:
    mol2: "templates/mol2/tris_neutral.mol2"
    net_charge: 0
    resname: "TR0"
    charge_method: "bcc"
    description: "Neutral Tris buffer"

  CI1:
    mol2: "templates/mol2/citrate_minus.mol2"
    net_charge: -1
    resname: "CI1"
    charge_method: "bcc"
    description: "Citrate(-1)"

  CI2:
    mol2: "templates/mol2/citrate2_minus.mol2"
    net_charge: -2
    resname: "CI2"
    charge_method: "bcc"
    description: "Citrate(-2)"

protonation:
  "7.4":
    overrides: {}
  "7.2":
    overrides: {}
  "4.9":
    overrides:
      "A:50": "HIP"
