"""Calculate RESP charges for a molecule using psiresp and Psi4."""

import argparse
import sys
from pathlib import Path

import psiresp
import qcelemental as qcel
from rdkit import Chem


def calculate_resp_charges(
    input_file: Path,
    output_file: Path,
    net_charge: int,
    basis_set: str = "6-31G*",
    functional: str = "B3LYP",
    n_conformers: int = 1,
    working_dir: Path = Path("resp_workdir"),
) -> None:
    """Run psiresp to generate RESP charges.

    Args:
        input_file: Path to input MOL2 or PDB
        output_file: Path to output MOL2 with RESP charges
        net_charge: Total molecule charge
        basis_set: QM basis set
        functional: QM functional
        n_conformers: Number of conformers to average over
        working_dir: Directory for QM scratch files
    """
    working_dir.mkdir(parents=True, exist_ok=True)

    print(f"Loading molecule from {input_file}...")
    # Load with RDKit to ensure connectivity and chemistry are correct
    # We disable sanitization to avoid failing on charged/protonated atoms
    if input_file.suffix == ".mol2":
        rdkit_mol = Chem.MolFromMol2File(str(input_file), removeHs=False, sanitize=False)
    elif input_file.suffix == ".pdb":
        rdkit_mol = Chem.MolFromPDBFile(str(input_file), removeHs=False, sanitize=False)
    else:
        raise ValueError(f"Unsupported file format: {input_file.suffix}")

    if rdkit_mol is None:
        raise ValueError(f"Failed to load molecule from {input_file}")

    # WORKAROUND: psiresp capture charges from RDKit formal charges during 'from_rdkit'.
    # If we don't set it here, conformers created during init will have charge 0.
    current_charge = Chem.GetFormalCharge(rdkit_mol)
    if current_charge != net_charge:
        print(f"Updating RDKit formal charge from {current_charge} to {net_charge}")
        # Try to find a Nitrogen that should be charged (e.g., in Tris+)
        charged_atom = None
        for atom in rdkit_mol.GetAtoms():
            if atom.GetSymbol() == "N":
                charged_atom = atom
                break
        
        if charged_atom is None:
            charged_atom = rdkit_mol.GetAtomWithIdx(0)
            
        charged_atom.SetFormalCharge(charged_atom.GetFormalCharge() + (net_charge - current_charge))

    # Manually update property cache with strict=False to allow "invalid" valences
    # which are actually correct for protonated species.
    rdkit_mol.UpdatePropertyCache(strict=False)

    # Create psiresp molecule
    print(f"Initializing psiresp molecule with charge={net_charge}, multiplicity=1")
    molecule = psiresp.Molecule.from_rdkit(rdkit_mol, charge=net_charge, multiplicity=1)

    # WORKAROUND: In some versions of psiresp (like 0.4.2), the charge on the 
    # underlying qcmol and conformers might not be correctly updated.
    # We rebuild the main qcmol and all conformers with the correct charge.
    def fix_qcmol_charge(qcmol, charge):
        qcmol_dict = qcmol.dict()
        qcmol_dict["molecular_charge"] = charge
        qcmol_dict["molecular_multiplicity"] = 1
        return qcel.models.Molecule(**qcmol_dict)

    molecule.qcmol = fix_qcmol_charge(molecule.qcmol, net_charge)
    for conformer in molecule.conformers:
        conformer.qcmol = fix_qcmol_charge(conformer.qcmol, net_charge)

    print(f"Molecule charge: {molecule.charge}, qcmol charge: {molecule.qcmol.molecular_charge}")
    if molecule.conformers:
        print(f"Conformer 0 charge: {molecule.conformers[0].qcmol.molecular_charge}")
    
    if n_conformers > 1:
        print(f"Generating {n_conformers} conformers...")
        molecule.generate_conformers(n_conformers=n_conformers)

    # Set up the job
    print(f"Setting up RESP job ({functional}/{basis_set})...")
    # In psiresp 0.4.2, we set options directly on the Job object
    job = psiresp.Job(
        molecules=[molecule],
        working_directory=str(working_dir),
    )
    
    # Configure QM options
    job.qm_esp_options.method = functional.lower()
    job.qm_esp_options.basis = basis_set.lower()
    
    # Enable two-stage RESP
    job.resp_options.stage_2 = True

    # Run the job (Requires Psi4 in the environment)
    print("Running QM calculations and RESP fitting...")
    try:
        job.run()
    except SystemExit as e:
        # Psi4 manages external execution in some cases
        print(f"Psi4 execution requested: {e}")
        # We might need to run the bash script generated by psiresp
        run_file = working_dir / "single_point" / "run_single_point.sh"
        if run_file.exists():
            print(f"Executing QM run script: {run_file}")
            # Add script directory to sys.path to allow importing topology_utils
            import os
            script_dir = os.path.dirname(os.path.abspath(__file__))
            if script_dir not in sys.path:
                sys.path.append(script_dir)
            from topology_utils import run_cmd
            # Run bash script from its own directory to ensure file paths match
            run_cmd(["bash", str(run_file)], run_file.parent, "psi4_run")
            # Run job again to collect results
            job.run()
        else:
            raise

    # Get charges and apply to molecule
    # job.charges is a list of arrays (one for each molecule)
    all_molecule_charges = job.charges
    if not all_molecule_charges:
        raise RuntimeError("No charges were calculated by psiresp")
    
    charges = all_molecule_charges[0]
    print(f"Calculated charges for first molecule: {charges}")

    # To save as MOL2, we need to inject the charges back into the RDKit molecule
    # or use another way to write MOL2. psiresp doesn't have a direct to_mol2.
    # We'll use the input MOL2 as a template and replace the charge column.
    
    _write_mol2_with_charges(input_file, output_file, charges)
    print(f"Wrote RESP charges to {output_file}")


def _write_mol2_with_charges(template_mol2: Path, output_mol2: Path, charges: list[float]) -> None:
    """Write a new MOL2 file replacing the charge column with new charges."""
    with open(template_mol2) as f:
        lines = f.readlines()

    output_lines = []
    current_section = None
    atom_idx = 0

    for line in lines:
        if line.startswith("@<TRIPOS>"):
            current_section = line.strip()
            # Only keep essential sections
            if current_section in ["@<TRIPOS>MOLECULE", "@<TRIPOS>ATOM", "@<TRIPOS>BOND"]:
                output_lines.append(line)
            continue
        
        if current_section == "@<TRIPOS>MOLECULE":
            # Change charge type in molecule section if it's the 5th line
            if len([l for l in output_lines if "@<TRIPOS>MOLECULE" in l]) == 1 and line.strip() in ["GASTEIGER", "BCC", "USER_CHARGES", "RESP"]:
                output_lines.append("RESP\n")
            else:
                output_lines.append(line)
        elif current_section == "@<TRIPOS>ATOM":
            if line.strip():
                parts = line.split()
                if len(parts) >= 9:
                    new_charge = f"{charges[atom_idx]:.6f}"
                    # ID NAME X Y Z TYPE SUBST_ID SUBST_NAME CHARGE
                    # Use standard spacing: 7, 5, 10, 10, 10, 5, 5, 8, 10
                    formatted = "{:>7} {:<5} {:>10.4f} {:>10.4f} {:>10.4f} {:<5} {:>5} {:<8} {:>10.6f}\n".format(
                        parts[0], parts[1], float(parts[2]), float(parts[3]), float(parts[4]), 
                        parts[5], parts[6], parts[7], float(new_charge)
                    )
                    output_lines.append(formatted)
                    atom_idx += 1
                else:
                    output_lines.append(line)
        elif current_section == "@<TRIPOS>BOND":
            output_lines.append(line)
        # Skip other sections like UNITY_ATOM_ATTR

    if atom_idx != len(charges):
        print(f"Warning: Atom count mismatch! MOL2 template had {atom_idx} atoms, but RESP returned {len(charges)} charges.")

    with open(output_mol2, "w") as f:
        f.writelines(output_lines)


def main():
    parser = argparse.ArgumentParser(description="Calculate RESP charges via psiresp")
    parser.add_argument("-i", "--input", type=Path, required=True, help="Input MOL2/PDB file")
    parser.add_argument("-o", "--output", type=Path, required=True, help="Output MOL2 file")
    parser.add_argument("-nc", "--net-charge", type=int, required=True, help="Net charge")
    parser.add_argument("-b", "--basis", default="6-31G*", help="Basis set")
    parser.add_argument("-f", "--functional", default="B3LYP", help="Functional")
    parser.add_argument("-n", "--n-conformers", type=int, default=1, help="Number of conformers")
    parser.add_argument("-w", "--workdir", type=Path, default=Path("resp_workdir"), help="Work directory")

    args = parser.parse_args()

    try:
        calculate_resp_charges(
            args.input,
            args.output,
            args.net_charge,
            basis_set=args.basis,
            functional=args.functional,
            n_conformers=args.n_conformers,
            working_dir=args.workdir,
        )
    except Exception as e:
        print(f"Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
